### ISSUE TITLE
apiCall 사용 방법

### ISSUE THREAD

**Issue by HiImConan** [prefragrance/prefragrance-client-migration#9]
@src/common/api 폴더 아래 있는 apiCall.ts와 constant/path.ts 및 types 폴더 아래 있는 타입용 ts 파일에 관하여 질문남깁니다.

1. api 호출해서 사용하는 프로세스가 
    1.  constant/path.ts의 ApiUrl 객체에 product 객체를 추가해준다(위 enum RouteUrl은 뭐에 쓰는 것인가요?).
    2. api폴더 아래에 product 폴더를 만들고 ProductApi class를 만들어준다.
    3. 자주 사용할 메소드들을 static으로 만들어준다. 이 때 response의 타입은 types 폴더 아래에 product.ts에 정리하여 export해준다.
    4. 이렇게 만든 api 호출 함수를 사용하고자 하는 컴포넌트에서 import한 뒤 사용한다
    로 이해하면 되나요?

2. 현재 main-page -> magazine 컴포넌트에서 'product/magazine/' url을 통해 데이터를 받아오려 코드를 아래와 같이 썼습니다
    ```
    useEffect(() => {
        apiCall
          .get(ApiUrl.product.magazine)
          .then((res) => console.log(res))
          .catch((err) => {
            console.log(err);
          });
      }, []);
     ```
    이렇게 코딩해서 브라우저 콘솔을 보니 `GET http://127.0.0.1:8000/api/product/magazine/ 500 (Internal Server Error)` 라는 에러 메세지가 떴습니다. api 호출 프로세스가 잘못된게 아니라면 스웨거에 나와있는 형태의 데이터들이 나와야하는거 아닌가요? 혹시 매거진 url은 아직 데이터가 없는걸 제가 모르고 있는건지 아리송합니다.

**Comment by zizonyoungjun** [comment]
맨 뒤에 '/' 이거 들어가서 생긴 에러는 아니겠지요?

**Comment by HiImConan** [comment]
useEffect 대신 react-query 쓰면 then이랑 catch 필요 없음
